before_install:
  - gem update --system

language: ruby
script: "./script/cibuild"
jdk: openjdk8
skip_cleanup: true
deploy:
  provider: script
  script: "./script/cibuild; ./script/cideploy"
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  addons:
  apt:
    packages:libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
