before_install:
  gem install bundler:2.1.4

language: ruby
script: "./script/cibuild"
jdk: openjdk8
deploy:
  provider: script
  script: "./script/cibuild; ./script/cideploy"
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  addons:
  apt:
    packages:libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
