language:
- ruby
- java
rvm:
- 2.6
script: "./script/cibuild"
jdk: openjdk8
deploy:
  provider: script
  skip_cleanup: true
  script: "./script/cibuild; ./script/cideploy"
  on:
    branch: master
exclude:
- vendor
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
